#Создает докер контейнер с версией mysql 8 и передает параметры mysql пароль рута, создает пользователя и задает емупароль, так же пробрасывает папки папка локальная : папка в контейнере
version: '3.1'
services:
  mysql_db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_USER: sys_temp
      MYSQL_PASSWORD: qwerty
    volumes:
      - /root/sql_part1/db-data:/var/lib/mysql/
      - /root/Working_with_data/sakila-db:/tmp/mysql/backup
